apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: backend-rs
  namespace: argocd
  labels:
    app: backend
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
  template:
    metadata:
      labels:
        app: backend
        tier: backend
    spec:
      containers: 
        - name: backend
          image: nginx:latest
          ports: 
            - containerPort: 8080


