apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: argocd
  label:
    app: backend
spec:
  selector:
    app: backend
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      target : 8080
  type: CLusterIP
